---

- name: Run own web-site
  hosts: all
  become: yes

  vars:
          source_folder: ~/ansible/MyWebSite/
          dest_file: /var/www/html
  tasks:
  - name: Check OS family
    debug: var=ansible_os_family
  - block: 
                - name: Install Httpd
                  yum: name=httpd state=latest
                - name: Copy file to nodes
                  copy: src={{ item }} dest={{ dest_file}} mode=0555
                  loop: " {{ source_folder }}/*.*"
                  notify: Restart httpd RedHat
                - name: Start httpd
                  service: name=httpd state=started enabled=yes
    when: ansible_os_family=="RedHat"

  - block:
                - name: Install Apache
                  apt: name=apache2 state=latest
                - name: Copy file to nodes
                  copy: src={{ source_file}} dest={{ dest_file}} mode=0555
                  notify: Restart Apache Debian
                - name: Start httpd
                  service: name=apache2 state=started enabled=yes
    when: ansible_os_family=="Debian"

  handlers:
  - name: Restart Apache Debian
    service: name=apache2 state=restarted 
  - name: Restart httpd RedHat
    service: name=httpd state=restarted
