---

- name: My debug and set_fact
  hosts: all
  become: yes


  vars:
          message1: Hello
          message2: World
          secret: FASFAGS123
  tasks:
          - name: Print secret var
            debug: 
                var: secret
          - debug:
                msg: "Secret word: {{ secret }}"
          - debug:
                msg: "Owner of instance {{ owner }}"
        
          - set_fact: full_message="{{ message1 }} {{ message2 }} from {{ owner }}"
         
        
          - debug:
                var: full_message
        
          - debug:
                var: ansible_distribution
        
          - shell: uptime
            register: results
        
          - debug:
                var: results
                      
